# Configuration for actions/labeler

area/documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '*.md'
      - 'LICENSE'

area/tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'

area/algorithm:
  - changed-files:
    - any-glob-to-any-file:
      - 'krkn_ai/algorithm/**/*'

area/chaos-engines:
  - changed-files:
    - any-glob-to-any-file:
      - 'krkn_ai/chaos_engines/**/*'

area/cli:
  - changed-files:
    - any-glob-to-any-file:
      - 'krkn_ai/cli/**/*'

area/models:
  - changed-files:
    - any-glob-to-any-file:
      - 'krkn_ai/models/**/*'

area/containers:
  - changed-files:
    - any-glob-to-any-file:
      - 'containers/**/*'
      - 'Containerfile'

area/ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/labeler.yml'
      - '.github/dependabot.yml'

area/scripts:
  - changed-files:
    - any-glob-to-any-file:
      - 'scripts/**/*'

area/utils:
  - changed-files:
    - any-glob-to-any-file:
      - 'krkn_ai/utils/**/*'
